- name: install apache2 package (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
     name:
      - apache2
      - libapache2-mod-php
       state: latest


- name: Change e-mail address for admin
  hosts: all
  become: true
  tasks:

    - name: Change ServerAdmin in httpd.conf
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      register: httpd  k

    - name: Restart Apache on Ubuntu
      service:
        name: apache2
        state: restarted
      when: httpd.changed
